export const UMBRAL_SONIDO = -60;
export const INTERVALO_ACTUALIZACION_AUDIO = 100;

export const RETRASO_DECREMENTO_RAPIDO = 50;
export const RETRASO_DECREMENTO_MEDIO = 250;
export const RETRASO_DECREMENTO_LENTO = 500;

export const TIEMPO_SIN_SONIDO_RAPIDO = 1500;
export const TIEMPO_SIN_SONIDO_MEDIO = 1000;
export const TIEMPO_SIN_SONIDO_LENTO = 500;

export const FACTOR_REVELADO = 5;
