export const POEMAS: string[][] = [
  [
    "hasta que",
    "mis dedos olviden",
    "que fueron silencio",
    "y aprendan a decirte",
    "todo lo que guardé",
    "en noches sin respuesta",
  ],
  [
    "hasta que",
    "el aire responda",
    "con algo más que vacío",
    "y deje de esquivarme",
    "cuando digo tu nombre",
    "como si aún doliera",
  ],
  [
    "hasta que",
    "la noche se quiebre",
    "en el ritmo de tus manos",
    "y el tiempo se detenga",
    "justo antes del olvido",
    "para volver a empezar",
  ],
  [
    "hasta que",
    "el eco diga tu nombre",
    "aunque no estés",
    "aunque nadie escuche",
    "aunque todo se apague",
    "menos esta insistencia",
  ],
  [
    "hasta que",
    "la piel entienda",
    "lo que nunca dijiste",
    "y traduzca en latidos",
    "lo que quedó pendiente",
    "entre dos silencios",
  ],
  [
    "hasta que",
    "el tiempo se rinda",
    "ante el ritmo",
    "y deje de empujarme",
    "hacia días sin vos",
    "donde todo es más lento",
  ],
];
